# Day 1

## Numpy Vectorization

Most operations are done element-wise i.e. using for loops such as

In [6]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

out = []

for i in range(len(a)):
    out.append(a[i] + b[i])
out

[5, 7, 9]

The sum product of array a and b are calculated by summing each 'element' of each array, hence the term element-wise. Whereas, a vectorized operation would operate every element in the array simultaneously.

In [7]:
a + b

array([5, 7, 9])

By using vectorization, more complex arrays or other datas can be operated more effieciently thanks to **The Broadcasting Rule**. The rule states that an array can be broadcasted to another array for each missing length the first array has, but the other length of the two arrays must have the same size. An example of this is

In [8]:
A = np.array([[0, 0, 0],
             [1, 1, 1],
             [2, 2, 2],
             [3, 3, 3]])

A + b

array([[4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

It can be seen that array b is broadcasted to each row of array A. A vectorized operation can also be done by using a boolean opearot that can result in a boolean array. An example of this is shown as

In [11]:
a > 1

array([False,  True,  True])

In [14]:
A+b > 6

array([[False, False, False],
       [False, False,  True],
       [False,  True,  True],
       [ True,  True,  True]])

Sometimes the data used needs to be standardized first. It can be done by using the equation

$$
x' = \frac{x'-x}{\sigma}
$$

In [20]:
c = np.array([1, 2, 3, 4, 5, 6])

(c - c.mean())/c.std()

array([-1.46385011, -0.87831007, -0.29277002,  0.29277002,  0.87831007,
        1.46385011])

## Functions

Functions can be made in python by using the 'def' command. For each functions made there must be corresponding arguments for the function to connect a value inserted and the operation done

In [38]:
def append_list(lst, lst_val):
    for i in range(len(lst_val)):
        lst.append(lst_val[i])
    return lst

lst = ["This", "is"]
add_list = ["a", "python", "list"]


append_list(lst, add_list)
lst

['This', 'is', 'a', 'python', 'list']

There are positional arguments that can be used for functions, which are args and kwargs. args are used for taking elements from lists and kwargs are used for taking elements from a dictionary. The difference between the two of these are the operator * and ** are used for taking elements from a list and dictionary, respectively.

## Decorators

Decorators are used to add functionality to a function that is created in python. By using decorators, it won't the function that has been created. Take this decorator function as an example.

In [64]:
def decorator_func(func):
    def wrapper_func():
        print('This wrapper goes before the function below')
        return func()
    return wrapper_func

Next, we create a function to use the decorator with.

In [65]:
def some_func():
    print('This is the function')

some_func()

This is the function


By adding the decorator before the function is used, the results will be.

In [66]:
@decorator_func
def deco_func():
    print('This is the function with decorator')

deco_func()

This wrapper goes before the function below
This is the function with decorator


It is shown here that the function that we created has another functionality that can be added through the wrapper function.

## Differential Equation Analysis

### Euler Method

Euler's method for differential equation analysis is to approximate the value ODEs by iterating the differential function to its initial value. Consider the following equation.

$$
\frac{dy(x)}{dx} = f(y(x),x)
$$

Assume that the function has an initial value of y = y0. The euler method to find the value from the equation will be iterated with the function itself multiplied by a step size of h. The function of the approximation y* is

$$
y^*(x) = y_0 + h.f(y(x),x)
$$

The smaller the value of h the more accurate it gets, but there needs to be a consideration in choosing a small h because the calculation time will increase as the smaller h gets.

### Runge Kutta 4th Order

Runge Kutta approximates the value of an ODE by iterating the initial value with four values which are k1, k2, k3, k4.

$$
k_1 = f(y^*(x_0), x_0)
$$

$$
k_2 = f(y^*(x_0) + k_1\frac{h}{2}, t_0 + \frac{h}{2})
$$

$$
k_2 = f(y^*(x_0) + k_2\frac{h}{2}, t_0 + \frac{h}{2})
$$

$$
k_4 = f(y^*(x_0) + k_3h, x_0 + h)
$$

The estimation value of the ODE based on the four values of k is determined by the function below.

$$
y^*(x_0 + h) = y^*(x_0) + h.\frac{k_1 + 2k_2 + 2k_3 + k_4}{6}
$$

The method works similarly to a weighted function shown by the value that are multiplied to each k. 

In [67]:
# Python class for both method