# Day 1

## Numpy Vectorization

Most operations are done element-wise i.e. using for loops such as

In [6]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

out = []

for i in range(len(a)):
    out.append(a[i] + b[i])
out

[5, 7, 9]

The sum product of array a and b are calculated by summing each 'element' of each array, hence the term element-wise. Whereas, a vectorized operation would operate every element in the array simultaneously.

In [7]:
a + b

array([5, 7, 9])

By using vectorization, more complex arrays or other datas can be operated more effieciently thanks to **The Broadcasting Rule**. The rule states that an array can be broadcasted to another array for each missing length the first array has, but the other length of the two arrays must have the same size. An example of this is

In [8]:
A = np.array([[0, 0, 0],
             [1, 1, 1],
             [2, 2, 2],
             [3, 3, 3]])

A + b

array([[4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

It can be seen that array b is broadcasted to each row of array A. A vectorized operation can also be done by using a boolean opearot that can result in a boolean array. An example of this is shown as

In [11]:
a > 1

array([False,  True,  True])

In [14]:
A+b > 6

array([[False, False, False],
       [False, False,  True],
       [False,  True,  True],
       [ True,  True,  True]])

Sometimes the data used needs to be standardized first. It can be done by using the equation

$$
x' = \frac{x-\bar{x}}{\sigma}
$$

In [20]:
c = np.array([1, 2, 3, 4, 5, 6])

(c - c.mean())/c.std()

array([-1.46385011, -0.87831007, -0.29277002,  0.29277002,  0.87831007,
        1.46385011])

## Functions

Functions can be made in python by using the 'def' command. For each functions made there must be corresponding arguments for the function to connect a value inserted and the operation done

In [38]:
def append_list(lst, lst_val):
    for i in range(len(lst_val)):
        lst.append(lst_val[i])
    return lst

lst = ["This", "is"]
add_list = ["a", "python", "list"]


append_list(lst, add_list)
lst

['This', 'is', 'a', 'python', 'list']

There are positional arguments that can be used for functions, which are args and kwargs. args are used for taking elements from lists and kwargs are used for taking elements from a dictionary. The difference between the two of these are the operator * and ** are used for taking elements from a list and dictionary, respectively.

## Decorators

Decorators are used to add functionality to a function that is created in python. By using decorators, it won't the function that has been created. Take this decorator function as an example.

In [64]:
def decorator_func(func):
    def wrapper_func():
        print('This wrapper goes before the function below')
        return func()
    return wrapper_func

Next, we create a function to use the decorator with.

In [65]:
def some_func():
    print('This is the function')

some_func()

This is the function


By adding the decorator before the function is used, the results will be.

In [66]:
@decorator_func
def deco_func():
    print('This is the function with decorator')

deco_func()

This wrapper goes before the function below
This is the function with decorator


It is shown here that the function that we created has another functionality that can be added through the wrapper function.

## Differential Equation Analysis

### Euler Method

Euler's method for differential equation analysis is to approximate the value ODEs by iterating the differential function to its initial value. Consider the following equation.

$$
\frac{dx(t)}{dt} = f(x(t),t)
$$

Assume that the function has an initial value of $x$ = $x_0$. The euler method to find the value from the equation will be iterated with the function itself multiplied by a step size of h. The function of the approximation x* is

$$
x^*(t) = x_0 + h.f(x(t),t)
$$

The smaller the value of $h$ the more accurate it gets, but there needs to be a consideration in choosing a small $h$ because the calculation time will increase as the smaller h gets.

### Runge Kutta 4th Order

Runge Kutta approximates the value of an ODE by iterating the initial value with four values which are $k_1$, $k_2$, $k_3$, $k_4$.

$$k_1 = f(x^*(t_0), t_0) \\
k_2 = f(x^*(t_0) + k_1\frac{h}{2}, t_0 + \frac{h}{2}) \\
k_3 = f(x^*(t_0) + k_2\frac{h}{2}, t_0 + \frac{h}{2}) \\
k_4 = f(x^*(t_0) + k_3h, t_0 + h)$$

The estimation value of the ODE based on the four values of k is determined by the function below.

$$
x^*(t_0 + h) = x^*(t_0) + h.\frac{k_1 + 2k_2 + 2k_3 + k_4}{6}
$$

The method works similarly to a weighted function shown by the value that are multiplied to each $k$. 

In [4]:
# Python class for both method
class diff_eq:
    def __init__ (self, t0, x0, target, step):
        self.t0 = t0
        self.x0 = x0
        self.target = target
        self.h = step
        self.xval = 0
        print("Values received")
        
    # Euler Method
    def euler(self, function):
        # Initiate the value of y
        self.xval = self.x0
        
        # Iterate until the value of x reaches the target x
        while self.t0 < self.target:
            self.xval = self.xval + self.h*function(self.t0, self.x0)
            self.t0 = self.t0 + self.h
        # Returns the value of y
        return self.xval
        
    # Runge Kutta 4th Order Method
    def rk4(self, function):
        # Number of iterations based on step size
        self.n = int((self.target - self.t0)/self.h)
        # Initiate the value of y
        self.xval = self.x0
            
        # Iterate until the value of x reaches the target x
        for i in range(1, self.n+1):
            # Runge Kutta formulas for each k
            k1 = self.h * function(self.t0, self.xval) 
            k2 = self.h * function(self.t0+0.5*self.h, self.xval+0.5*k1) 
            k3 = self.h * function(self.t0+0.5*self.h, self.xval+0.5*k2) 
            k4 = self.h * function(self.t0+self.h, self.xval+k3)
            
            # Update values
            self.xval = self.xval + 1.0*(k1 + 2 * k2 + 2 * k3 + k4)/6.0
            self.t0 = self.t0 + self.h
        return self.xval

In [6]:
def dxdy(t, x):
    return ((t - x)/2)

# Euler method test
euval = diff_eq(0, 1, 2, 0.2)
print("The value by using euler method: " + str(euval.euler(dxdy)))

# Runge kutta method test
rkval = diff_eq(0, 1, 2, 0.2)
print("The value by using runge kutta method: " + str(rkval.rk4(dxdy)))

Values received
The value by using euler method: 0.9999999999999999
Values received
The value by using runge kutta method: 1.1036393232374955


# Day 2

## Truncation Error

Assume that there exists an equation of x which is stated as

$$
x' = \frac{dx}{dt} = f(x,t)
$$

When using the euler method for calculating the approximation value of x, there will be an error generated because of the approximation. The error generated is called as the **Truncation Error**. For the equation above, the truncation error by using the euler method for approximation for each step of iteration is stated as

$$
O(h^2) = \frac{h^2}{2}x''(\tilde{t_i})
$$

Where the value of x'' is the second order derivation of x by t, or in other form it is stated as

$$
x''(t_i) = f_t(t,x(t)) + f_x(t,x(t))f(t,x(t))
$$

$f_t$ and $f_x$ are both the partial derivation of the equation by t and x respectively. The value of $\tilde{t_i}$ is the number between $x_i$ and $x_{i+1}$, hence

$$
\tilde{x_i} = \frac{x_{i+1}-x_i}{2}
$$

Seeing that $x'$ is equal to $f(x,t)$, hence the formula of $O(h^2)$ can also be written as

$$
O(h^2) = \frac{h^2}{2}f'(x_i,t_i)
$$

The truncation error of the euler method is defined by $O(h^2)$. Whereas for a higher order the truncation error, say an order of $n$, it would change the truncation error equation to $O(h^{n+1})$. The formula of $O(h^n)$ is stated as

$$
O(h^n) = \frac{h^n}{n!}f^{(n-1)}(x_i,t_i)
$$

Referring back to the RK4 method, based on its name, we can determine that it would have a truncation error of $n+1$ based on its order. Hence, the truncation error of the RK4 method would be $O(h^5)$.